export const USER_ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  FINANCE: "FINANCE",
  INSPECTOR: "INSPECTOR",
  VIEWER: "VIEWER"
};

export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard:view",
  COMPANY_VIEW: "company:view",
  COMPANY_MANAGE: "company:manage",
  LICENSE_VIEW: "license:view",
  LICENSE_MANAGE: "license:manage",
  PAYMENT_VIEW: "payment:view",
  PAYMENT_MANAGE: "payment:manage",
  REPORT_VIEW: "report:view",
  USER_VIEW: "user:view",
  USER_MANAGE: "user:manage"
};

export const ROLE_PERMISSIONS = {
  [USER_ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [USER_ROLES.ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.COMPANY_MANAGE,
    PERMISSIONS.LICENSE_VIEW,
    PERMISSIONS.LICENSE_MANAGE,
    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.PAYMENT_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.USER_VIEW
  ],
  [USER_ROLES.FINANCE]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.LICENSE_VIEW,
    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.PAYMENT_MANAGE,
    PERMISSIONS.REPORT_VIEW
  ],
  [USER_ROLES.INSPECTOR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.COMPANY_MANAGE,
    PERMISSIONS.LICENSE_VIEW,
    PERMISSIONS.LICENSE_MANAGE,
    PERMISSIONS.REPORT_VIEW
  ],
  [USER_ROLES.VIEWER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.LICENSE_VIEW,
    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.REPORT_VIEW
  ]
};

export function getRolePermissions(role) {
  return ROLE_PERMISSIONS[role] ?? [];
}

export function hasPermission(role, permission) {
  return getRolePermissions(role).includes(permission);
}
